import { PlayerId, ManagerId } from '../shared/ids';
import { PlayerAttributes, Surface, isPhysicalAttribute } from './PlayerAttributes';
import { PhysicalCeilings } from './PlayerGenerationPolicy';
import { DomainEvent } from '../shared/DomainEvent';
import { TrainingFocus, TrainingPolicy, applyCoachBonus, applyPotentialDiminishingReturns } from './TrainingPolicy';

/**
 * A dormant graduation-carryover bonus parked on this player at an
 * age-band crossing, waiting to be consumed by their first real result
 * in the new band. Named distinctly from (rather than importing) the
 * Competition/Ranking bounded context's own
 * `GraduationCarryover.DormantCarryoverBonus` — per CLAUDE.md principle
 * #5, `domain/player` doesn't import from `domain/ranking` (a
 * different bounded context); the two types are structurally
 * identical on purpose, so the application layer (which already spans
 * both contexts, e.g. SimulateMatchUseCase) can pass a value straight
 * through without any explicit mapping. Player itself has zero opinion
 * about what a "band" means or how the bonus is computed/consumed —
 * see GraduationCarryover.ts for that; Player only stores and clears
 * this one field.
 */
export interface PlayerDormantCarryoverBonus {
  readonly targetBand: 'senior' | 'u14' | 'u16';
  readonly bonusPoints: number;
}

export type PlayerLifecycleStage = 'youth' | 'prime' | 'decline' | 'retired';

export interface PlayerProps {
  id: PlayerId;
  name: string;
  /** Set once at hire time, purely a presentation concern (a flag next
   * to the player's name) — the domain attaches no gameplay meaning to
   * it. Free-text rather than an enum/ISO-code type on purpose: no
   * country reference data exists anywhere else in the domain, and
   * adding one for a display-only field would be exactly the kind of
   * scope CLAUDE.md warns against. */
  nationality: string;
  ageInWeeks: number;
  managerId: ManagerId | null;
  attributes: PlayerAttributes;
  stage: PlayerLifecycleStage;
  fatigue: number; // 0 (fresh) – 100 (exhausted)
  /** The training focus a manager has committed this player to for
   * upcoming weekly ticks (see TrainingPolicy) — null means no
   * standing focus, so no delta applies until one is set. Distinct
   * from applyTraining(), which applies a delta immediately given a
   * focus; this field only records the *standing selection* that
   * AdvanceWorldWeekUseCase reads each week. */
  currentFocus: TrainingFocus | null;
  /** Hidden ceiling generated at creation time (see
   * PlayerGenerationPolicy.GeneratedPlayer.potentialCeiling), carried
   * unchanged from whatever talent-pool candidate or custom player
   * this Player originated from. NEVER exposed via any DTO — see
   * playerDto.ts, which deliberately does not read this field.
   * ORPHANED by applyTraining() as of the per-attribute training
   * redesign (docs/training-redesign-per-attribute.md): technical
   * attributes are never gated by any ceiling, physical attributes are
   * gated by their own physicalCeilings entry below instead, and
   * mental attributes are never trained at all — nothing reads this
   * field for training anymore. Still generated and stored (it also
   * feeds PlayerGenerationPolicy's scouting-noise calculation at
   * generation time, unrelated to training), left independent rather
   * than derived from physicalCeilings per that doc's "deliberately
   * deferred, not solved now" section — not removed, just no longer
   * load-bearing for training. */
  potentialCeiling: number;
  /** Hidden per-physical-attribute training ceilings — set once at
   * generation time (see PlayerGenerationPolicy.GeneratedPlayer.physicalCeilings),
   * carried unchanged from whatever talent-pool candidate or custom
   * player this Player originated from. NEVER exposed via any DTO —
   * see playerDto.ts, which deliberately does not read this field.
   * This IS what applyTraining() gates physical-attribute training
   * against now (see that method's doc comment) — potentialCeiling
   * above is the one that's orphaned, not this one. */
  physicalCeilings: PhysicalCeilings;
  /** null = no pending graduation-carryover bonus. Set by
   * AdvanceWorldWeekUseCase the week this player crosses a junior
   * age-band boundary; cleared by SimulateMatchUseCase the moment it's
   * consumed by this player's first real (points > 0) ranking-ledger
   * entry in the target band. See PlayerDormantCarryoverBonus's doc
   * comment above and domain/ranking/GraduationCarryover.ts for the
   * mechanism. */
  dormantCarryoverBonus: PlayerDormantCarryoverBonus | null;
  /** True only for a player generated by GenesisSeedFillOnlyPlayersUseCase
   * or converted from an expired TalentPoolCandidate (see
   * RefreshTalentPoolUseCase and docs/tournament-fill-system.md) — never
   * set by hire() (a manager's own roster is never fill-only). Always
   * paired with managerId: null, but means something more specific than
   * that alone: a RELEASED player also has managerId null yet
   * fillOnly stays false for them, since a release doesn't turn a
   * once-managed player into a fill-only NPC-like entity, it just frees
   * their slot. AdvanceWorldWeekUseCase reads this flag to decide
   * whether to auto-train toward the weakest attribute (fillOnly
   * players have no manager to set a TrainingFocus) or to leave
   * currentFocus-driven training untouched (every other player,
   * including a released one). There is deliberately no path back to
   * false, and no manager-facing route ever claims a fillOnly player —
   * see docs/tournament-fill-system.md's "Open question" section for
   * why permanent fill-only status was chosen over some broader
   * reclaim mechanism. */
  fillOnly: boolean;
}

/** Aggregate root for the Player & Roster bounded context.
 *
 * SRP note: Player owns identity + lifecycle transitions only. It does
 * NOT know how to age itself week-over-week (that's
 * PlayerAgingService's job, since aging curves are a policy that may
 * change independently of what a Player *is*), and it does NOT know
 * how to simulate a match (that's the Match Simulation Engine's job,
 * consuming only the immutable PlayerAttributes snapshot).
 */
export class Player {
  private readonly _domainEvents: DomainEvent[] = [];

  private constructor(private props: PlayerProps) {}

  static hire(
    id: PlayerId,
    name: string,
    ageInWeeks: number,
    attributes: PlayerAttributes,
    managerId: ManagerId,
    /** Optional so existing call sites (mostly tests that don't care
     * about nationality) don't all need updating — HirePlayerUseCase,
     * the real product entry point, always passes a real value. */
    nationality = 'XX',
    /** Same "optional trailing param, real entry points always pass a
     * real value" convention as `nationality` above — see this field's
     * doc comment on PlayerProps. Defaults to 100 (skill max), i.e. "no
     * meaningful ceiling," so every pre-existing call site that never
     * heard of potential ceilings keeps training at full, unthrottled
     * rate exactly as before this feature existed. Real entry points
     * (ClaimTalentPoolCandidateUseCase, CreateCustomPlayerUseCase)
     * always pass the real generated value. */
    potentialCeiling = 100,
    /** Same "optional trailing param, real entry points always pass a
     * real value" convention as potentialCeiling above. Defaults to
     * {100,100,100} — "no meaningful ceiling" per attribute — so every
     * pre-existing call site that never heard of per-attribute
     * ceilings is unaffected. Real entry points (ClaimTalentPoolCandidateUseCase,
     * CreateCustomPlayerUseCase) always pass the real generated value. */
    physicalCeilings: PhysicalCeilings = { speed: 100, stamina: 100, strength: 100 },
  ): Player {
    const player = new Player({
      id,
      name,
      nationality,
      ageInWeeks,
      managerId,
      attributes,
      stage: 'youth',
      fatigue: 0,
      currentFocus: null,
      potentialCeiling,
      physicalCeilings,
      dormantCarryoverBonus: null,
      fillOnly: false,
    });
    player._domainEvents.push({
      type: 'PlayerHired',
      occurredAt: new Date(),
      payload: { playerId: id, managerId },
    });
    return player;
  }

  /** Produces a fill-only free agent: no manager (managerId: null),
   * `fillOnly: true` (see PlayerProps.fillOnly's doc comment), and no
   * standing training focus — AdvanceWorldWeekUseCase auto-computes one
   * fresh every tick for a fillOnly player instead. Unlike hire(),
   * `stage` is a required parameter rather than hardcoded 'youth': a
   * fillOnly player can be generated at any non-retired age (see
   * GenesisSeedFillOnlyPlayersUseCase's wide age range), so the caller
   * must compute the real stage for that age via an AgingPolicy rather
   * than this factory silently assuming youth the way hire() safely can
   * (every real hire()/claim call site only ever generates a
   * 14-16-year-old). Emits a distinct 'FillOnlyPlayerGenerated' event
   * rather than 'PlayerHired' — nobody hired this player, so reusing
   * that event's name/payload shape (which promises a real managerId)
   * would be misleading to any consumer. */
  static generateFillOnly(
    id: PlayerId,
    name: string,
    ageInWeeks: number,
    stage: PlayerLifecycleStage,
    attributes: PlayerAttributes,
    nationality = 'XX',
    potentialCeiling = 100,
    physicalCeilings: PhysicalCeilings = { speed: 100, stamina: 100, strength: 100 },
  ): Player {
    const player = new Player({
      id,
      name,
      nationality,
      ageInWeeks,
      managerId: null,
      attributes,
      stage,
      fatigue: 0,
      currentFocus: null,
      potentialCeiling,
      physicalCeilings,
      dormantCarryoverBonus: null,
      fillOnly: true,
    });
    player._domainEvents.push({
      type: 'FillOnlyPlayerGenerated',
      occurredAt: new Date(),
      payload: { playerId: id },
    });
    return player;
  }

  /** Rehydrates a persisted player (repository adapters only). Unlike
   * hire(), this is not a domain action — it emits NO events; the
   * player being loaded back is not being hired again. */
  static reconstitute(props: PlayerProps): Player {
    return new Player({ ...props });
  }

  get id() {
    return this.props.id;
  }

  get name() {
    return this.props.name;
  }

  get nationality() {
    return this.props.nationality;
  }

  get currentFocus() {
    return this.props.currentFocus;
  }

  get ageInWeeks() {
    return this.props.ageInWeeks;
  }

  get managerId() {
    return this.props.managerId;
  }

  get attributes() {
    return this.props.attributes;
  }

  get stage() {
    return this.props.stage;
  }

  get fatigue() {
    return this.props.fatigue;
  }

  /** Hidden — see PlayerProps.potentialCeiling's doc comment. Read by
   * applyTraining() and by repository adapters that need to persist
   * it; never by anything building an HTTP-facing DTO. */
  get potentialCeiling() {
    return this.props.potentialCeiling;
  }

  /** Hidden — see PlayerProps.physicalCeilings' doc comment. Never
   * read by anything building an HTTP-facing DTO. */
  get physicalCeilings() {
    return this.props.physicalCeilings;
  }

  get dormantCarryoverBonus() {
    return this.props.dormantCarryoverBonus;
  }

  get fillOnly(): boolean {
    return this.props.fillOnly;
  }

  isRetired(): boolean {
    return this.props.stage === 'retired';
  }

  /** Applies a single training session for one focus (surface, or a
   * single technical/physical attribute — see TrainingFocus; mental is
   * never a valid focus at all). The BASE delta is computed by the
   * injected policy, never by Player: this method's job is only to
   * apply whatever delta it's given, not to decide how much a session
   * is worth in a vacuum. What Player DOES own is the further
   * adjustments intrinsic to this specific player/manager rather than
   * a swappable policy concern:
   *  - for a PHYSICAL attribute only, scaling the base delta down as
   *    that specific attribute's own hidden ceiling
   *    (physicalCeilings[attribute]) approaches (see
   *    applyPotentialDiminishingReturns) — a ceiling is a property of
   *    the player's own attribute, not of the training policy.
   *    Technical-attribute training is NEVER run through a ceiling at
   *    all (see docs/training-redesign-per-attribute.md: open-ended,
   *    bounded only by training investment and decline-stage decay),
   *    and neither is surface-affinity training — see
   *    applyPotentialDiminishingReturns' own doc comment.
   *  - scaling the (already ceiling-adjusted, for physical attributes)
   *    delta UP by the manager's coach, if any (see applyCoachBonus) —
   *    a coach's benefit is general training efficiency, unrelated to
   *    any specific attribute's own ceiling, so unlike the ceiling
   *    adjustment this DOES apply to surface, technical, AND physical
   *    training alike.
   *
   * `coachRating` defaults to null (no coach) so every pre-existing
   * call site that never heard of coaches keeps training exactly as
   * before this feature existed — same "optional trailing param, real
   * entry points pass a real value" convention as hire()'s
   * nationality/potentialCeiling params. The real caller
   * (AdvanceWorldWeekUseCase) looks up the manager's coach and passes
   * its coachRating through. */
  applyTraining(focus: TrainingFocus, policy: TrainingPolicy, coachRating: number | null = null): void {
    if (this.isRetired()) {
      throw new Error(`Cannot train retired player ${this.props.id}`);
    }
    const baseDelta = policy.computeDelta(focus, this.props.stage);
    if (focus.kind === 'surface') {
      const delta = applyCoachBonus(baseDelta, coachRating);
      const updatedAttributes = this.props.attributes.trainedOnSurface(focus.surface, delta);
      this.props = { ...this.props, attributes: updatedAttributes };
      return;
    }
    const { attribute } = focus;
    const ceilingAdjusted = isPhysicalAttribute(attribute)
      ? applyPotentialDiminishingReturns(baseDelta, this.props.attributes.attributeValue(attribute), this.props.physicalCeilings[attribute])
      : baseDelta; // technical: no ceiling, ever
    const delta = applyCoachBonus(ceilingAdjusted, coachRating);
    const updatedAttributes = this.props.attributes.trainedOnAttribute(attribute, delta);
    this.props = { ...this.props, attributes: updatedAttributes };
  }

  /** Records the standing training focus a manager has committed this
   * player to — does NOT apply any attribute delta itself. The delta
   * is applied later, once per game week, by AdvanceWorldWeekUseCase
   * calling applyTraining() during the weekly tick (the same cadence
   * PlayerAgingService already ages players on). Passing null clears
   * the focus, so no training delta applies until a new one is set. */
  setTrainingFocus(focus: TrainingFocus | null): void {
    if (this.isRetired()) {
      throw new Error(`Cannot set training focus for retired player ${this.props.id}`);
    }
    this.props = { ...this.props, currentFocus: focus };
  }

  applyMatchFatigue(fatigueDelta: number): void {
    this.props = {
      ...this.props,
      fatigue: Math.max(0, Math.min(100, this.props.fatigue + fatigueDelta)),
    };
  }

  recoverFatigue(amount: number): void {
    this.applyMatchFatigue(-amount);
  }

  /** Small, automatic surface-affinity growth from having actually
   * played a match on this surface — called by SimulateMatchUseCase
   * for both participants after every match, alongside
   * applyMatchFatigue (same "direct Player mutator, no policy/ceiling
   * indirection" shape, since like fatigue this is a fixed per-match
   * side effect, not a weekly manager decision the way TrainingFocus
   * itself is). This is the replacement for surface affinity's only
   * previous growth path (the manual TrainingFocus='surface' weekly
   * choice via applyTraining) — the per-attribute training redesign
   * (docs/training-redesign-per-attribute.md) removed surface as a
   * cluster-training axis on the assumption automatic match-play
   * growth would take over, but that replacement was never actually
   * built until now; without this, surface affinity was frozen at its
   * initial value for any manager who never happened to pick that
   * exact weekly focus. Deliberately no retirement guard, unlike
   * applyTraining — matches applyMatchFatigue's own precedent, since a
   * completed match is a fact that already happened, not a request
   * that can be rejected. */
  applyMatchSurfaceGrowth(surface: Surface, gain: number): void {
    this.props = {
      ...this.props,
      attributes: this.props.attributes.trainedOnSurface(surface, gain),
    };
  }

  /** Advances lifecycle stage and age. Called by PlayerAgingService,
   * never invoked directly by application code, so aging rules stay
   * centralized in one place. */
  advanceWeek(newAgeInWeeks: number, newStage: PlayerLifecycleStage, updatedAttributes: PlayerAttributes): void {
    const wasRetired = this.isRetired();
    this.props = {
      ...this.props,
      ageInWeeks: newAgeInWeeks,
      stage: newStage,
      attributes: updatedAttributes,
    };
    if (!wasRetired && newStage === 'retired') {
      this._domainEvents.push({
        type: 'PlayerRetired',
        occurredAt: new Date(),
        payload: { playerId: this.props.id },
      });
    }
  }

  releaseFromManager(): void {
    this.props = { ...this.props, managerId: null };
  }

  /** Records a fresh dormant graduation-carryover bonus (called by
   * AdvanceWorldWeekUseCase at a band crossing) or clears one after
   * it's been consumed (called by SimulateMatchUseCase) — same setter
   * either way, since "record a new one" and "clear the old one"
   * aren't different operations from Player's point of view, just
   * different values. Silently overwrites any bonus already sitting
   * here: see PlayerDormantCarryoverBonus's doc comment on why an
   * unconsumed bonus becoming moot at the next crossing is correct,
   * not a bug. */
  setDormantCarryoverBonus(bonus: PlayerDormantCarryoverBonus | null): void {
    this.props = { ...this.props, dormantCarryoverBonus: bonus };
  }

  pullDomainEvents(): DomainEvent[] {
    const events = [...this._domainEvents];
    this._domainEvents.length = 0;
    return events;
  }
}
