import { ManagerId, Player, PlayerGenerationPolicy, PlayerId, RandomSource } from '@tennis-manager/domain';
import { BillingPort, EventPublisherPort, PlayerRepository } from '../ports/ports';
import { PRO_ROSTER_CAP } from './rosterCap';
import { TALENT_POOL_AGE_RANGE } from './talentPoolAgeRange';

export interface CreateCustomPlayerCommand {
  playerId: PlayerId;
  managerId: ManagerId;
  name: string;
  nationality: string;
}

/**
 * Pro-only, credit-gated alternative to browsing the talent pool: a
 * manager supplies name/nationality directly instead of waiting for a
 * matching candidate to appear. Costs one custom-player credit, earned
 * one at a time on each confirmed Stripe subscription renewal (see
 * BillingPort.consumeCustomPlayerCredit).
 *
 * FAIRNESS CONSTRAINT — read this before touching attribute generation
 * here: the resulting player's attributes are generated by the exact
 * SAME PlayerGenerationPolicy every talent pool candidate uses, called
 * with the exact same TALENT_POOL_AGE_RANGE, with no special-cased
 * odds, bands, or age for this path. Paying only buys bypassing pool
 * competition (choose your own name/nationality, skip waiting for the
 * right candidate to appear) — never a stat advantage, and still no
 * manager-chosen age (the generated ageInWeeks wins, same as any pool
 * candidate's). This is CLAUDE.md principle #1 applied directly: if
 * you find yourself tempted to give a custom player better rarity
 * odds "since they paid for it," that is exactly the pay-to-win
 * pattern this project explicitly rejects. Don't.
 */
export class CreateCustomPlayerUseCase {
  constructor(
    private readonly players: PlayerRepository,
    private readonly events: EventPublisherPort,
    private readonly billing: BillingPort,
    private readonly generationPolicy: PlayerGenerationPolicy,
    private readonly random: RandomSource,
  ) {}

  async execute(command: CreateCustomPlayerCommand): Promise<Player> {
    const isPro = await this.billing.isProSubscriber(command.managerId);
    if (!isPro) {
      throw new Error(`Manager ${command.managerId} must be a Manager Pro subscriber to create a custom player`);
    }

    const currentRoster = await this.players.findByManager(command.managerId);
    if (currentRoster.length >= PRO_ROSTER_CAP) {
      throw new Error(`Manager ${command.managerId} roster is full (${currentRoster.length}/${PRO_ROSTER_CAP})`);
    }

    const creditSpent = await this.billing.consumeCustomPlayerCredit(command.managerId);
    if (!creditSpent) {
      throw new Error(`Manager ${command.managerId} has no custom player credits remaining`);
    }

    // Same generation policy, same age range, as any pool candidate —
    // see this class's doc comment. Only name/nationality are the
    // manager's choice.
    const generated = this.generationPolicy.generate(this.random, TALENT_POOL_AGE_RANGE);

    const player = Player.hire(
      command.playerId,
      command.name,
      generated.ageInWeeks,
      generated.attributes,
      command.managerId,
      command.nationality,
      generated.potentialCeiling,
      generated.physicalCeilings,
      generated.talent,
    );
    await this.players.save(player);
    await this.events.publish(player.pullDomainEvents());
    return player;
  }
}
